# Generated by Django 4.2.19 on 2025-03-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='private or public'),
        ),
    ]
